# We can call this function using the new name
another_reference_to_func3(10, 42)
# 52
